spring.application.name=url-shortner
#spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.uri=mongodb://localhost:27017/productdb
server.port=8082
#spring.data.redis.host=*** (add yours redis information)
spring.data.redis.port=17808
#spring.data.redis.password=*** (add yours redis information)
