spring.application.name=url-shortner
#spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.uri=mongodb://localhost:27017/productdb
server.port=8082
spring.data.redis.host=redis-17808.crce281.ap-south-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=17808
spring.data.redis.password=W58OdCfbOs8PCsmrJDi7nc5tJ2eto1Cx
